### PR TITLE
NodeJS: Replace `SimpleLogRecordProcessor` by `BatchLogRecordProcessor`

### LINKED ISSUE #1798: `Concurrent export limit reached` during intensive logging
**Describe the bug**
During intensive logging wrapper throws:
```
{
    "message": "{\"stack\":\"Error: Concurrent export limit reached\\n    
at e.export (/opt/wrapper.js:1:193931)\\n    
at e.export (/opt/wrapper.js:1:169793)\\n    
at /opt/wrapper.js:1:232711\\n    
at AsyncLocalStorage.run (node:async_hooks:346:14)\\n    
at s.with (/opt/wrapper.js:1:189112)\\n    
at e.with (/opt/wrapper.js:1:171909)\\n    
at /opt/wrapper.js:1:232667\\n    
at new Promise (<anonymous>)\\n    
at Object._export (/opt/wrapper.js:1:232634)\\n    
at n (/opt/810.wrapper.js:1:10706)\",\"message\":\"Concurrent export limit reached\",\"name\":\"Error\"}",
    "message_id": "9b3a6870-4b39-44d7-94eb-d66e0e70b1a3"
}
```

**Steps to reproduce**
emit +35 logs in 100ms

**What did you expect to see?**
No error.

**What did you see instead?**
Error

**What version of collector/language SDK version did you use?**

Version: (e.g., `v0.58.0`, `v1.11.0`, etc): 
- opentelemetry-collector-amd64-0_14_0:1
- opentelemetry-nodejs-0_13_0:1

**What language layer did you use?**
Config: NodeJs

**Additional context**
It might be a solution to replace `SimpleLogRecordProcessor` with `BatchLogRecordProcessorBase`.

### PR DESCRIPTION
**Pull request by rndD**
Fixes #1798 

`SimpleLogRecordProcessor` has a [concurrency limit of 30](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/otlp-exporter-base/src/otlp-export-delegate.ts#L64) simultaneous export promises. After hitting this limit, the Processor throws the error `Error: Concurrent export limit reached`. 

To avoid the error during heavy logging, we can use [BatchLogRecordProcessor](https://github.com/open-telemetry/opentelemetry-js/blob/db0616fb3738f02ac45c43126ada0c9e5e24bbb3/experimental/packages/sdk-logs/src/platform/browser/export/BatchLogRecordProcessor.ts#L21). 

`BatchLogRecordProcessor` can already be configured via [env vars](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/sdk-logs/src/export/BatchLogRecordProcessorBase.ts#L51), which is good for lambda layer:
* OTEL_BLRP_MAX_EXPORT_BATCH_SIZE
* OTEL_BLRP_MAX_QUEUE_SIZE
* OTEL_BLRP_SCHEDULE_DELAY 
* OTEL_BLRP_EXPORT_TIMEOUT

### CODE REVIEW

**Comment by rndD** [comment]
cc @serkan-ozal

File: nodejs/packages/layer/src/wrapper.ts [hunk 1]
```diff
@@ -464,15 +464,15 @@ async function initializeLoggerProvider(
...
+      new BatchLogRecordProcessor(logExporter),
     );
     logs.setGlobalLoggerProvider(loggerProvider);
   }
 
   // Logging for debug
   if (logLevel === DiagLogLevel.DEBUG) {
     loggerProvider.addLogRecordProcessor(
-      new SimpleLogRecordProcessor(new ConsoleLogRecordExporter()),
+      new BatchLogRecordProcessor(new ConsoleLogRecordExporter()),
```
Comment (serkan-ozal) [inline nodejs/packages/layer/src/wrapper.ts]: I think, we can keep `SimpleLogRecordProcessor` for `ConsoleLogRecordExporter` as we did for traces.

**Comment by serkan-ozal** [comment]
Thanks @rndD, 
That's fast :)
I have added one minor comment.

**Comment by serkan-ozal** [comment]
@rndD PR look good, but there is lint issue. Can you fix that by `npm run lint:fix`

**Comment by rndD** [comment]
> That's fast :)

Had it ready. I was testing if the `batchProcessor` solves the problem. I might say that the publishing layer took a while to do manually. I appreciate all the infrastructure you built to make layers publicly available.

Any chance you can trigger nodejs layer publish after merging this one?

**Comment by serkan-ozal** [comment]
Hi @rndD,

I think we should wait this PR (https://github.com/open-telemetry/opentelemetry-lambda/pull/1789) got approved and merged for the next release, but not sure what @tylerbenson thinks

**Review by serkan-ozal — APPROVED** [review]

**Comment by tylerbenson** [comment]
LGTM.
